session.join:
  - "Join the session you fucking nerds! Game mode is ${gameMode}."
  - "Put the J down and hit the join button! Game mode is ${gameMode}."
session.conclude:
  - "This concludes joining the session."
  - "Ok NOW you can smoke the ganja."
  - "DRAW YOUR HANDS!"
user.chosen:
  - "${username} is your leader. Good luck with that fuckup."
  - "${username} is your leader and the knight is totally Tim. Trust me."
user.joined:
  - "${username} joined the session."
  - "${username} left the session."
  - "${username} ???? the session."
  - "${username} fucked the session. It was really gross."
user.role:
  - "Hey, your role is ${role}"
user.team:
  - "Hey, your team is ${team}"
error.not.enough.players:
  - "Motherfuckers!! You need 4 or more people to join!"
  - "C'mon guys. Get it together."
  - "JEEZUS. You need 4 or more."
error.teams.not.balanced:
  - "Ugh you dont have enough players for even teams!"
error.not.implemented:
  - "I'm lazy and havent implemented this game mode. Choose another one."